# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kalman_filter <- function(B0, P0, Dt, At, Ft, Ht, Qt, Rt, yt) {
    .Call(`_TCSDecomp_kalman_filter`, B0, P0, Dt, At, Ft, Ht, Qt, Rt, yt)
}

kalman_smoother <- function(B_TL, B_TT, P_TL, P_TT, Ft) {
    .Call(`_TCSDecomp_kalman_smoother`, B_TL, B_TT, P_TL, P_TT, Ft)
}

rcpparma_hello_world <- function() {
    .Call(`_TCSDecomp_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_TCSDecomp_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_TCSDecomp_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_TCSDecomp_rcpparma_bothproducts`, x)
}

